"""add symptom_queries table

Revision ID: a5c1dee2f0e6
Revises: 18b885681c47
Create Date: 2026-05-17 12:59:58.985199
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a5c1dee2f0e6'
down_revision: Union[str, None] = '18b885681c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symptoms_text', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_queries_created_at'), 'symptom_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_symptom_queries_user_id'), 'symptom_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_queries_user_id'), table_name='symptom_queries')
    op.drop_index(op.f('ix_symptom_queries_created_at'), table_name='symptom_queries')
    op.drop_table('symptom_queries')
    # ### end Alembic commands ###
